language: ruby
env:
  - ARUBA_TIMEOUT=240
before_install:
  - gem update --system
  - rvm @default,@global do gem uninstall bundler -v 2.0.1 -x
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
branches:
  only:
    - master
install:
  - "bundle install --retry 3 --jobs 8"
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
